/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class space_bestysh_scanner_Scanner */

#ifndef _Included_space_bestysh_scanner_Scanner
#define _Included_space_bestysh_scanner_Scanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     space_bestysh_scanner_Scanner
 * Method:    scannerCrop
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_space_bestysh_scanner_Scanner_scannerCrop
  (JNIEnv *, jobject, jobject);

/*
 * Class:     space_bestysh_scanner_Scanner
 * Method:    scannerCropPoint
 * Signature: (Landroid/graphics/Bitmap;)[I
 */
JNIEXPORT jfloatArray JNICALL Java_space_bestysh_scanner_Scanner_scannerCropPoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     space_bestysh_scanner_Scanner
 * Method:    scannerPointTransform
 * Signature: (Landroid/graphics/Bitmap;[I)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_space_bestysh_scanner_Scanner_scannerPointTransform
  (JNIEnv *, jobject, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
